import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font.normal]
# family = "MesloLGLDZ Nerd Font Mono"
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.italic]
# family = "MesloLGLDZ Nerd Font Mono"
family = "FiraCode Nerd Font Mono"
style = "Italic"

